import {SAMPLE,classesForDay,currentClass,nextClass,freePeriods,conflicts,fmtMinutes,sortClasses} from './timetable.js';
import {load,patch,addTask,toggleTask,applyTheme,setTheme} from './store.js';
import {ask} from './ai.js';
import {downloadIcs} from './calendar.js';
import {initNotifications,requestNotifications,remindBeforeClass} from './notifications.js';
import {level,progress,title,badges} from './gamification.js';
import {setView,getView} from './navigation.js';

const state=load();let timetable=SAMPLE;let aiBusy=false;let deferredInstall=null;
const main=document.querySelector('#main');const toastEl=document.querySelector('#toast');
const esc=s=>String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const dayName=()=>new Date().toLocaleDateString('en-US',{weekday:'long'});
function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>toastEl.classList.remove('show'),2600)}
function shellStats(){const today=classesForDay(timetable,dayName());const cur=currentClass(timetable);const nxt=nextClass(timetable);const free=freePeriods(timetable,dayName()).filter(x=>x.end-x.start>=30);return {today,cur,nxt,free}}
function classHtml(c,cur=false){return `<article class="class-card ${cur?'current':''}"><div><span class="tag">${esc(c.code||'CLASS')}</span><h3>${esc(c.course)}</h3><div class="muted">${esc(c.teacher||'Faculty')} · ${esc(c.room||'Room TBD')}</div></div><div class="time">${esc(c.start)}<br><span class="muted">${esc(c.end)}</span></div></article>`}
function renderHome(){const s=shellStats();const xp=load().xp;return `<section class="hero"><div class="hero-card"><span class="eyebrow">${new Date().toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long'})}</span><h1>${s.cur?`You're in ${esc(s.cur.course)}.`:`Your campus, simplified.`}</h1><p class="muted">${s.cur?`Room ${esc(s.cur.room)} · ends at ${s.cur.end}.`:(s.nxt?`Next: ${esc(s.nxt.course)} at ${s.nxt.start} in ${esc(s.nxt.room)}.`:'No upcoming classes loaded.')}</p><div class="chips"><button class="primary" data-view="timetable">Open timetable</button><button class="ghost" data-view="ai">Ask SaiU AI</button></div></div><div class="card"><span class="eyebrow">Student XP</span><div class="metric">Level ${level(xp)}</div><p>${title(level(xp))}</p><div class="progress"><i style="width:${progress(xp)}%"></i></div><small class="muted">${xp} XP · ${100-progress(xp)} to next level</small></div></section><div class="grid grid-3"><div class="card"><div class="muted">Today's classes</div><div class="metric">${s.today.length}</div></div><div class="card"><div class="muted">30+ min free slots</div><div class="metric">${s.free.length}</div></div><div class="card"><div class="muted">Conflicts</div><div class="metric">${conflicts(timetable).length}</div></div></div><div class="section-head"><h2>Today</h2><button class="ghost" data-action="calendar">Export calendar</button></div><div class="schedule">${s.today.length?s.today.map(c=>classHtml(c,s.cur?.id===c.id)).join(''):'<div class="empty">No classes today.</div>'}</div>`}
function renderTimetable(){const days=['Monday','Tuesday','Wednesday','Thursday','Friday'];return `<div class="section-head"><div><span class="eyebrow">Live schedule</span><h1>Timetable</h1></div><button class="primary" data-action="calendar">Export .ics</button></div><div class="grid grid-2">${days.map(d=>`<section class="card"><div class="section-head"><h2>${d}</h2><span class="tag">${classesForDay(timetable,d).length} classes</span></div><div class="schedule">${classesForDay(timetable,d).map(c=>classHtml(c,currentClass(timetable)?.id===c.id)).join('')||'<div class="empty">Free day 🎉</div>'}</div></section>`).join('')}</div><section class="card" style="margin-top:16px"><h2>Free-time finder</h2><p class="muted">30+ minute gaps today</p><div class="chips">${freePeriods(timetable,dayName()).map(p=>`<span class="tag">${fmtMinutes(p.start)}–${fmtMinutes(p.end)}</span>`).join('')||'<span class="muted">No gaps.</span>'}</div></section>`}
function renderAI(){return `<section class="card"><span class="eyebrow">SaiU intelligence</span><h1>Ask SaiU AI</h1><p class="muted">Works offline from your timetable. Optionally connect a trusted backend endpoint in Settings; no provider secret belongs in this browser app.</p><div class="chips">${['When is my next class?','What is my schedule today?','When am I free tomorrow?','Do I have any conflicts?'].map(q=>`<button class="chip" data-question="${esc(q)}">${esc(q)}</button>`).join('')}</div><div class="ai-row"><textarea id="aiInput" placeholder="Ask about your schedule…"></textarea><button id="aiSend" class="primary">Ask</button></div><div id="aiAnswer" class="answer hidden"></div></section>`}
function renderPlanner(){const s=load();return `<div class="section-head"><div><span class="eyebrow">Focus mode</span><h1>Planner</h1></div><span class="tag">${s.tasks.filter(t=>t.done).length}/${s.tasks.length} done</span></div><section class="card"><form id="taskForm" class="ai-row"><input id="taskInput" class="search" placeholder="Add assignment, exam or study task" required><button class="primary">Add</button></form><div style="margin-top:14px">${s.tasks.map(t=>`<label class="check"><input type="checkbox" data-task="${t.id}" ${t.done?'checked':''}><span style="text-decoration:${t.done?'line-through':'none'}">${esc(t.title)}</span></label>`).join('')||'<div class="empty">Your planner is clear.</div>'}</div></section>`}
function renderMore(){const s=load();return `<div class="section-head"><div><span class="eyebrow">System</span><h1>More</h1></div></div><div class="grid grid-2"><section class="card"><h2>Preferences</h2><div class="statline"><span>Theme</span><select id="themeSelect"><option value="system" ${s.theme==='system'?'selected':''}>System</option><option value="light" ${s.theme==='light'?'selected':''}>Light</option><option value="dark" ${s.theme==='dark'?'selected':''}>Dark</option></select></div><div class="statline"><span>Notifications</span><button class="ghost" id="notifyBtn">Enable</button></div><div class="statline"><span>AI endpoint</span><input id="aiEndpoint" class="search" value="${esc(localStorage.getItem('saiu_ai_endpoint')||'')}" placeholder="Optional HTTPS backend URL"></div><button class="primary" id="saveSettings">Save settings</button></section><section class="card"><h2>Gamification</h2><div class="metric">Level ${level(s.xp)}</div><p>${title(level(s.xp))}</p><div class="chips">${badges(s).map(b=>`<span class="tag">🏆 ${esc(b)}</span>`).join('')||'<span class="muted">Earn badges by using the planner.</span>'}</div><hr style="border:0;border-top:1px solid var(--line);margin:18px 0"><h3>Architecture</h3><p class="muted">Offline-first store · timetable engine · optional AI gateway · calendar export · notifications · PWA caching · CI tests.</p></section></div>`}
function render(){const v=getView();main.innerHTML=v==='home'?renderHome():v==='timetable'?renderTimetable():v==='ai'?renderAI():v==='planner'?renderPlanner():renderMore();document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));bind();main.focus({preventScroll:true})}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{setView(b.dataset.view);render()});document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>{document.querySelector('#aiInput').value=b.dataset.question});document.querySelectorAll('[data-task]').forEach(b=>b.onchange=()=>{toggleTask(b.dataset.task);render()});const form=document.querySelector('#taskForm');if(form)form.onsubmit=e=>{e.preventDefault();const input=document.querySelector('#taskInput');if(input.value.trim()){addTask(input.value.trim());toast('Task added +5 XP');render()}};const send=document.querySelector('#aiSend');if(send)send.onclick=async()=>{if(aiBusy)return;const input=document.querySelector('#aiInput');const answer=document.querySelector('#aiAnswer');if(!input.value.trim())return;aiBusy=true;send.disabled=true;answer.classList.remove('hidden');answer.textContent='Thinking…';answer.textContent=await ask(input.value.trim(),timetable);aiBusy=false;send.disabled=false};const theme=document.querySelector('#themeSelect');if(theme)theme.onchange=()=>{setTheme(theme.value);applyTheme()};const save=document.querySelector('#saveSettings');if(save)save.onclick=()=>{localStorage.setItem('saiu_ai_endpoint',document.querySelector('#aiEndpoint').value.trim());toast('Settings saved')};const notify=document.querySelector('#notifyBtn');if(notify)notify.onclick=async()=>{const p=await requestNotifications();toast(p==='granted'?'Notifications enabled':`Notifications: ${p}`)};document.querySelectorAll('[data-action="calendar"]').forEach(b=>b.onclick=()=>downloadIcs(timetable))}

document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{setView(b.dataset.view);render()});document.querySelector('.brand').onclick=()=>{setView('home');render()};document.querySelector('#themeBtn').onclick=()=>{const s=load();setTheme(s.theme==='dark'?'light':'dark');applyTheme()};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;document.querySelector('#installBtn').classList.remove('hidden')});document.querySelector('#installBtn').onclick=async()=>{if(deferredInstall){deferredInstall.prompt();deferredInstall=null}};
initNotifications();applyTheme();render();setInterval(()=>{if(getView()==='home'||getView()==='timetable')render()},30000);const n=nextClass(timetable);if(n)remindBeforeClass(n,10);window.SaiU={timetable,load,render};
