import {SAMPLE,classesForDay,currentClass,nextClass,freePeriods,conflicts,fmtMinutes,timetableStats} from './timetable-safe.js';
import {load,addTask,toggleTask,applyTheme,setTheme} from './store.js';
import {ask} from './ai.js';
import {downloadIcs} from './calendar.js';
import {initNotifications,requestNotifications,remindBeforeClass} from './notifications.js';
import {level,progress,title,badges,recordActivity} from './gamification.js';
import {setView,getView} from './navigation.js';
import {CATALOG,schoolById,yearById} from './catalog.js';
import {loadRemoteTimetable,clearRemoteCache} from './remote.js';

load();let timetable=SAMPLE;let aiBusy=false;let deferredInstall=null;let source='demo';let loading=true;let refreshToken=0;
const main=document.querySelector('#main'),toastEl=document.querySelector('#toast');
const esc=s=>String(s??'').replace(/[&<>\\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;'}[c]));
const dayName=()=>new Date().toLocaleDateString('en-US',{weekday:'long'});
function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>toastEl.classList.remove('show'),2600)}
function selection(){const schoolId=localStorage.getItem('saiu_school')||CATALOG.schools[0].id;const school=schoolById(schoolId);const yearId=localStorage.getItem('saiu_year')||school.years[0]?.id;const year=yearById(school,yearId);const section=localStorage.getItem('saiu_section')||year?.sections?.[0]||null;return {schoolId,yearId:year?.id,section}}
function syncDiscoveredSections(items,selectionValue){const school=schoolById(selectionValue.schoolId),year=yearById(school,selectionValue.yearId);if(!year)return;const discovered=[...new Set(items.map(row=>row.section).filter(v=>Number.isInteger(v)&&v>0))].sort((a,b)=>a-b);const updated=[...school.years];const idx=updated.findIndex(y=>y.id===year.id);if(idx>=0){updated[idx]={...updated[idx],sections:discovered};const catIndex=CATALOG.schools.findIndex(s=>s.id===school.id);if(catIndex>=0)CATALOG.schools[catIndex]={...CATALOG.schools[catIndex],years:updated}}const saved=localStorage.getItem('saiu_section');if(saved&&!discovered.some(section=>String(section)===String(saved)))localStorage.removeItem('saiu_section')}
async function refreshTimetable(notify=true){const token=++refreshToken;loading=true;render();const selected=selection();const result=await loadRemoteTimetable(selected);if(token!==refreshToken)return;timetable=result.timetable;source=result.source;if(source==='live'||source==='offline-cache')syncDiscoveredSections(timetable,selected);loading=false;if(notify)toast(source==='live'?'Live timetable synced':source==='offline-cache'?'Using offline timetable':'Demo timetable loaded');render();const n=nextClass(timetable);if(n)remindBeforeClass(n,10)}
function shellStats(){const today=classesForDay(timetable,dayName());const cur=currentClass(timetable);const nxt=nextClass(timetable);const free=freePeriods(timetable,dayName()).filter(x=>x.end-x.start>=30);return {today,cur,nxt,free}}
function classHtml(c,cur=false){return `<article class="class-card ${cur?'current':''}"><div><span class="tag">${esc(c.code||'CLASS')}</span><h3>${esc(c.course)}</h3><div class="muted">${esc(c.teacher||'Faculty')} · ${esc(c.room||'Room TBD')}</div></div><div class="time">${esc(c.start)}<br><span class="muted">${esc(c.end)}</span></div></article>`}
function selectorHtml(){const sel=selection(),school=schoolById(sel.schoolId),year=yearById(school,sel.yearId);return `<section class="control-card"><div><span class="eyebrow">Personal timetable</span><h2>${esc(school.short)} · ${esc(year?.label||'Year')}</h2><p class="muted">${source==='live'?'🟢 Live source':source==='offline-cache'?'🟡 Offline cache':'🔵 Demo data'}${loading?' · syncing…':''}</p></div><div class="selectors"><select id="schoolSelect">${CATALOG.schools.map(s=>`<option value="${s.id}" ${s.id===school.id?'selected':''}>${esc(s.short)} — ${esc(s.name)}</option>`).join('')}</select><select id="yearSelect">${(school.years||[]).map(y=>`<option value="${y.id}" ${y.id===year?.id?'selected':''}>${esc(y.label)}</option>`).join('')}</select>${year?.sections?.length?`<select id="sectionSelect">${year.sections.map(s=>`<option value="${esc(s)}" ${String(s)===String(sel.section)?'selected':''}>Section ${esc(s)}</option>`).join('')}</select>`:'<span class="tag">No section filter</span>'}<button class="primary" id="syncBtn">Sync now</button></div></section>`}
function renderHome(){const s=shellStats(),xp=load().xp,stats=timetableStats(timetable);return `${selectorHtml()}<section class="hero"><div class="hero-card"><span class="eyebrow">${new Date().toLocaleDateString('en-IN',{weekday:'long',day:'numeric',month:'long'})}</span><h1>${s.cur?`You're in ${esc(s.cur.course)}.`:`Your campus, simplified.`}</h1><p class="muted">${s.cur?`Room ${esc(s.cur.room)} · ends at ${s.cur.end}.`:(s.nxt?`Next: ${esc(s.nxt.course)} at ${s.nxt.start} in ${esc(s.nxt.room)}.`:'No upcoming classes loaded.')}</p><div class="countdown" id="countdown">${s.cur?'LIVE NOW':s.nxt?`Next class ${esc(s.nxt.start)}`:'Free time'}</div><div class="chips"><button class="primary" data-view="timetable">Open timetable</button><button class="ghost" data-view="ai">Ask SaiU AI</button><button class="ghost" data-action="share">Share schedule</button></div></div><div class="card"><span class="eyebrow">Student XP</span><div class="metric">Level ${level(xp)}</div><p>${title(level(xp))}</p><progress class="progress-bar" max="100" value="${progress(xp)}" aria-label="Progress to next level"></progress><small class="muted">${xp} XP · ${100-progress(xp)} to next level</small></div></section><div class="grid grid-4"><div class="card"><div class="muted">Classes</div><div class="metric">${stats.classes}</div></div><div class="card"><div class="muted">Days</div><div class="metric">${stats.days}</div></div><div class="card"><div class="muted">Free slots</div><div class="metric">${s.free.length}</div></div><div class="card"><div class="muted">Conflicts</div><div class="metric">${stats.conflicts}</div></div></div><div class="section-head"><h2>Today</h2><button class="ghost" data-action="calendar">Export calendar</button></div><div class="schedule">${s.today.length?s.today.map(c=>classHtml(c,s.cur?.id===c.id)).join(''):'<div class="empty">No classes today. Enjoy the free time. 🎉</div>'}</div>`}
function renderTimetable(){const days=['Monday','Tuesday','Wednesday','Thursday','Friday'];return `${selectorHtml()}<div class="section-head"><div><span class="eyebrow">Live schedule</span><h1>Timetable</h1></div><div class="chips"><button class="primary" data-action="calendar">Export .ics</button><button class="ghost" data-action="share">Share</button></div></div><div class="grid grid-2">${days.map(d=>`<section class="card"><div class="section-head"><h2>${d}</h2><span class="tag">${classesForDay(timetable,d).length} classes</span></div><div class="schedule">${classesForDay(timetable,d).map(c=>classHtml(c,currentClass(timetable)?.id===c.id)).join('')||'<div class="empty">Free day 🎉</div>'}</div></section>`).join('')}</div><section class="card card-spaced"><h2>Free-time finder</h2><p class="muted">Useful gaps of at least 30 minutes today.</p><div class="chips">${freePeriods(timetable,dayName()).filter(p=>p.end-p.start>=30).map(p=>`<span class="tag">${fmtMinutes(p.start)}–${fmtMinutes(p.end)} · ${p.end-p.start} min</span>`).join('')||'<span class="muted">No gaps.</span>'}</div></section><section class="card card-spaced"><h2>Schedule health</h2><p class="muted">${conflicts(timetable).length?`⚠️ ${conflicts(timetable).length} overlapping classes need attention.`:'✅ No timetable conflicts detected.'}</p></section>`}
function renderAI(){return `<section class="card"><span class="eyebrow">SaiU intelligence</span><h1>Ask SaiU AI</h1><p class="muted">Local-first schedule intelligence works without an AI provider. Optional backend integration is supported without putting provider secrets in this browser.</p><div class="chips">${['When is my next class?','What is my schedule today?','When am I free tomorrow?','Do I have any conflicts?','What is my longest free slot?'].map(q=>`<button class="chip" data-question="${esc(q)}">${esc(q)}</button>`).join('')}</div><div class="ai-row"><textarea id="aiInput" placeholder="Ask about your timetable…"></textarea><button id="aiSend" class="primary">Ask</button></div><div id="aiAnswer" class="answer hidden"></div></section><section class="card"><h2>Compare schedules</h2><p class="muted">Load another schedule in another browser/device and use the local common-free-time engine, or connect a trusted backend for friends.</p><button class="ghost" data-action="share">Share my schedule</button></section>`}
function renderPlanner(){const s=load();return `<div class="section-head"><div><span class="eyebrow">Focus mode</span><h1>Planner</h1></div><span class="tag">${s.tasks.filter(t=>t.done).length}/${s.tasks.length} done</span></div><section class="card"><form id="taskForm" class="ai-row"><input id="taskInput" class="search" placeholder="Add assignment, exam or study task" required><button class="primary">Add</button></form><div class="tasks-list">${s.tasks.map(t=>`<label class="check"><input type="checkbox" data-task="${t.id}" ${t.done?'checked':''}><span class="task-label ${t.done?'task-done':''}">${esc(t.title)}</span></label>`).join('')||'<div class="empty">Your planner is clear.</div>'}</div></section>`}
function renderMore(){const s=load(),sel=selection(),school=schoolById(sel.schoolId),year=yearById(school,sel.yearId);return `<div class="section-head"><div><span class="eyebrow">System</span><h1>More</h1></div></div><div class="grid grid-2"><section class="card"><h2>Preferences</h2><div class="statline"><span>Theme</span><select id="themeSelect"><option value="system" ${s.theme==='system'?'selected':''}>System</option><option value="light" ${s.theme==='light'?'selected':''}>Light</option><option value="dark" ${s.theme==='dark'?'selected':''}>Dark</option></select></div><div class="statline"><span>Notifications</span><button class="ghost" id="notifyBtn">Enable</button></div><div class="statline"><span>AI endpoint</span><input id="aiEndpoint" class="search" value="${esc(localStorage.getItem('saiu_ai_endpoint')||'')}" placeholder="Optional HTTPS backend URL"></div><button class="primary" id="saveSettings">Save settings</button><button class="danger" id="clearCache">Clear timetable cache</button></section><section class="card"><h2>Your setup</h2><p><b>${esc(school.short)}</b> · ${esc(year?.label||'Year')} ${sel.section?`· Section ${esc(sel.section)}`:''}</p><p class="muted">${source==='live'?'Live Google Sheets source':source==='offline-cache'?'Cached source — offline mode':'Demo fallback'}.</p><h3>Gamification</h3><div class="metric">Level ${level(s.xp)}</div><p>${title(level(s.xp))}</p><div class="chips">${badges(s).map(b=>`<span class="tag">🏆 ${esc(b)}</span>`).join('')||'<span class="muted">Earn badges by using the planner.</span>'}</div></section></div>`}
function render(){const v=getView();main.innerHTML=v==='home'?renderHome():v==='timetable'?renderTimetable():v==='ai'?renderAI():v==='planner'?renderPlanner():renderMore();document.querySelectorAll('.bottom-nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===v));bind()}
async function share(){const lines=timetable.map(c=>`${c.day} ${c.start}-${c.end} ${String(c.course||'').replace(/[\r\n]/g,' ')} ${String(c.room||'').replace(/[\r\n]/g,' ')}`);const text=`SaiU V2 — ${selection().schoolId} ${selection().yearId}\n${lines.join('\n')}`;try{if(navigator.share)await navigator.share({title:'My SaiU timetable',text});else{await navigator.clipboard.writeText(text);toast('Schedule copied to clipboard')}}catch(e){if(e?.name!=='AbortError')toast('Share unavailable')}}
function bind(){document.querySelectorAll('[data-view]').forEach(b=>b.onclick=()=>{setView(b.dataset.view);render()});document.querySelectorAll('[data-question]').forEach(b=>b.onclick=()=>{document.querySelector('#aiInput').value=b.dataset.question});document.querySelectorAll('[data-task]').forEach(b=>b.onchange=()=>{toggleTask(b.dataset.task);render()});document.querySelectorAll('[data-action="share"]').forEach(b=>b.onclick=share);document.querySelectorAll('[data-action="calendar"]').forEach(b=>b.onclick=()=>downloadIcs(timetable));const form=document.querySelector('#taskForm');if(form)form.onsubmit=e=>{e.preventDefault();const i=document.querySelector('#taskInput');if(i.value.trim()){addTask(i.value.trim());toast('Task added +5 XP');render()}};const send=document.querySelector('#aiSend');if(send)send.onclick=async()=>{if(aiBusy)return;const i=document.querySelector('#aiInput'),a=document.querySelector('#aiAnswer');if(!i.value.trim())return;aiBusy=true;send.disabled=true;a.classList.remove('hidden');a.textContent='Thinking…';a.textContent=await ask(i.value.trim(),timetable);aiBusy=false;send.disabled=false};const theme=document.querySelector('#themeSelect');if(theme)theme.onchange=()=>{setTheme(theme.value);applyTheme()};const save=document.querySelector('#saveSettings');if(save)save.onclick=()=>{const endpoint=document.querySelector('#aiEndpoint').value.trim();if(endpoint&&!/^https:\/\//i.test(endpoint))return toast('AI endpoint must use HTTPS');localStorage.setItem('saiu_ai_endpoint',endpoint);toast('Settings saved')};const notify=document.querySelector('#notifyBtn');if(notify)notify.onclick=async()=>toast(`Notifications: ${await requestNotifications()}`);const clear=document.querySelector('#clearCache');if(clear)clear.onclick=()=>{clearRemoteCache();toast('Cache cleared');refreshTimetable()};const sync=document.querySelector('#syncBtn');if(sync)sync.onclick=()=>refreshTimetable();const school=document.querySelector('#schoolSelect');if(school)school.onchange=()=>{localStorage.setItem('saiu_school',school.value);localStorage.removeItem('saiu_year');localStorage.removeItem('saiu_section');refreshTimetable()};const year=document.querySelector('#yearSelect');if(year)year.onchange=()=>{localStorage.setItem('saiu_year',year.value);localStorage.removeItem('saiu_section');refreshTimetable()};const section=document.querySelector('#sectionSelect');if(section)section.onchange=()=>{localStorage.setItem('saiu_section',section.value);refreshTimetable()}}

document.querySelectorAll('.bottom-nav button').forEach(b=>b.onclick=()=>{setView(b.dataset.view);render()});document.querySelector('.brand').onclick=()=>{setView('home');render()};document.querySelector('#themeBtn').onclick=()=>{const s=load();if(s.theme==='system'){setTheme('dark')}else if(s.theme==='dark'){setTheme('light')}else{setTheme('system')}applyTheme()};window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredInstall=e;document.querySelector('#installBtn').classList.remove('hidden')});document.querySelector('#installBtn').onclick=async()=>{if(deferredInstall){await deferredInstall.prompt();deferredInstall=null}};initNotifications();applyTheme();recordActivity();render();refreshTimetable(false);setInterval(()=>{if(getView()==='home'||getView()==='timetable'){const wasFocused=document.activeElement;const scrollY=window.scrollY;render();if(wasFocused&&wasFocused.id){const restored=document.getElementById(wasFocused.id);if(restored)restored.focus()}window.scrollTo(0,scrollY)}},30000);window.SaiU={get timetable(){return timetable},selection,refresh:refreshTimetable};