import {sortClasses} from './timetable.js';
const escapeText=value=>String(value??'').replace(/\\/g,'\\\\').replace(/\r?\n/g,'\\n').replace(/;/g,'\\;').replace(/,/g,'\\,');
const pad=n=>String(n).padStart(2,'0');
const dayCode={Sunday:'SU',Monday:'MO',Tuesday:'TU',Wednesday:'WE',Thursday:'TH',Friday:'FR',Saturday:'SA'};
function localDateForDay(day,base=new Date()){const dayIndex={Sunday:0,Monday:1,Tuesday:2,Wednesday:3,Thursday:4,Friday:5,Saturday:6}[day];if(dayIndex==null)return null;const d=new Date(base);d.setDate(d.getDate()+((dayIndex-d.getDay()+7)%7));return d}
function dtLocal(date,time){const [h,m]=String(time).split(':').map(Number);if(!Number.isInteger(h)||!Number.isInteger(m)||h<0||h>23||m<0||m>59)return null;const d=new Date(date);d.setHours(h,m,0,0);return `${d.getFullYear()}${pad(d.getMonth()+1)}${pad(d.getDate())}T${pad(d.getHours())}${pad(d.getMinutes())}00`}
function dtUtc(date=new Date()){return `${date.getUTCFullYear()}${pad(date.getUTCMonth()+1)}${pad(date.getUTCDate())}T${pad(date.getUTCHours())}${pad(date.getUTCMinutes())}${pad(date.getUTCSeconds())}Z`}
export function ics(items,title='SaiU V2 Timetable'){const lines=['BEGIN:VCALENDAR','VERSION:2.0','PRODID:-//SaiU V2//EN','CALSCALE:GREGORIAN','METHOD:PUBLISH','X-WR-CALNAME:'+escapeText(title),'X-WR-TIMEZONE:Asia/Kolkata'];for(const c of sortClasses(items)){const date=localDateForDay(c.day);const start=dtLocal(date,c.start),end=dtLocal(date,c.end);if(!date||!start||!end)continue;const uid=escapeText(c.id||`${c.day}-${c.start}-${c.course}`);const code=dayCode[c.day];lines.push('BEGIN:VEVENT',`UID:${uid}@saiu-v2`,`DTSTAMP:${dtUtc()}`,`DTSTART;TZID=Asia/Kolkata:${start}`,`DTEND;TZID=Asia/Kolkata:${end}`,`RRULE:FREQ=WEEKLY;BYDAY=${code||''}`,`SUMMARY:${escapeText(c.course)}`,`LOCATION:${escapeText(c.room||'')}`,`DESCRIPTION:${escapeText(`${c.code||''}${c.teacher?` — ${c.teacher}`:''}`)}`,'STATUS:CONFIRMED','SEQUENCE:0','END:VEVENT')}lines.push('END:VCALENDAR');return lines.join('\r\n')+'\r\n'}
export function downloadIcs(items){const blob=new Blob([ics(items)],{type:'text/calendar;charset=utf-8'});const a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='saiu-timetable.ics';document.body.appendChild(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
