const KEY='saiu-v2-reminders';
let registration=null;
const scheduled=new Map();
const DAY_INDEX={Sunday:0,Monday:1,Tuesday:2,Wednesday:3,Thursday:4,Friday:5,Saturday:6};
const readReminders=()=>{try{const value=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(value)?value.filter(x=>x&&Number.isFinite(x.targetMs)):[]}catch{return[]}};
const writeReminders=items=>localStorage.setItem(KEY,JSON.stringify(items));
const prune=()=>{const cutoff=Date.now()-86400000;const items=readReminders().filter(x=>x.targetMs>cutoff);writeReminders(items);return items};
export async function initNotifications(){if(!('serviceWorker' in navigator))return null;try{registration=await navigator.serviceWorker.ready;restoreReminders();return registration}catch{return null}}
export async function notify(title,body,tag='saiu-v2'){if(!registration||typeof Notification==='undefined'||Notification.permission!=='granted')return false;try{await registration.showNotification(title,{body,tag});return true}catch{return false}}
export async function requestNotifications(){if(!('Notification' in window))return 'unsupported';return Notification.requestPermission()}
function reminderKey(c,targetMs,minutes){return `${String(c.id||`${c.day}-${c.start}-${c.course}`)}:${targetMs}:${minutes}`}
function schedule(record){const delay=record.targetMs-Date.now();const key=reminderKey(record,record.targetMs,record.minutes);if(delay<=0||delay>=7*86400000)return;if(scheduled.has(key))return;const timer=setTimeout(()=>{scheduled.delete(key);const remaining=readReminders().filter(x=>reminderKey(x,x.targetMs,x.minutes)!==key);writeReminders(remaining);void notify('Upcoming class',`${record.course} starts in ${record.minutes} minutes — ${record.room||'room TBD'}`,`saiu-v2:${record.id||record.course}:${record.targetMs}`)},delay);scheduled.set(key,timer)}
function restoreReminders(){clearScheduledReminders();const now=Date.now();const items=prune();for(const record of items){if(record.targetMs>now&&record.targetMs-now<7*86400000)schedule(record);else if(record.targetMs<=now&&now-record.targetMs<=5*60000)void notify('Class reminder',`${record.course} may be starting now — ${record.room||'room TBD'}`,`saiu-v2:catchup:${record.targetMs}`)}}
export function remindBeforeClass(c,minutes=10,now=new Date()){if(!c)return;const dayIndex=DAY_INDEX[c.day];if(dayIndex==null)return;const target=new Date(now);const delta=(dayIndex-target.getDay()+7)%7;target.setDate(target.getDate()+delta);const [h,m]=String(c.start).split(':').map(Number);if(!Number.isInteger(h)||!Number.isInteger(m)||h<0||h>23||m<0||m>59)return;target.setHours(h,m,0,0);const targetMs=target.getTime();const delay=targetMs-now.getTime()-minutes*60000;if(delay<=0||delay>=7*86400000)return;const id=String(c.id||`${c.day}-${c.start}-${c.course}`);const items=prune().filter(x=>!(String(x.id)===id&&x.minutes===minutes));const record={id,day:c.day,start:c.start,end:c.end,course:String(c.course||'Class'),room:String(c.room||''),minutes:Number(minutes),targetMs};items.push(record);writeReminders(items);schedule(record)}
export function clearScheduledReminders(){for(const timer of scheduled.values())clearTimeout(timer);scheduled.clear()}
export function clearReminderStore(){clearScheduledReminders();localStorage.removeItem(KEY)}
