const KEY='saiu-v2-state';
const LEGACY_ACADEMICS='saiu-v2-academics';
const LEGACY_GAMIFICATION='saiu-v2-gamification';
const defaults={theme:'system',school:null,section:null,tasks:[],xp:0,streak:0,lastActive:null,lastOpen:null,installDismissed:false,attendanceTarget:75,attendance:{},exams:[],studyPlans:[],xpEvents:{},schemaVersion:2};
const cloneDefaults=()=>({...defaults,tasks:[],attendance:{},exams:[],studyPlans:[],xpEvents:{}});
const localIso=date=>{const d=new Date(date);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
const isoNow=()=>localIso(new Date());
function parse(raw){try{return raw?JSON.parse(raw):null}catch{return null}}
function migrate(){const base=cloneDefaults();const legacyAcademics=parse(localStorage.getItem(LEGACY_ACADEMICS));const legacyGame=parse(localStorage.getItem(LEGACY_GAMIFICATION));const migrated={...base,...(parse(localStorage.getItem(KEY))||{})};if(legacyAcademics){if(!migrated.attendance||!Object.keys(migrated.attendance).length)migrated.attendance=legacyAcademics.attendance&&typeof legacyAcademics.attendance==='object'?legacyAcademics.attendance:{};if(!migrated.exams?.length)migrated.exams=Array.isArray(legacyAcademics.exams)?legacyAcademics.exams:[];if(!migrated.studyPlans?.length)migrated.studyPlans=Array.isArray(legacyAcademics.studyPlans)?legacyAcademics.studyPlans:[];if(migrated.attendanceTarget===75&&Number.isFinite(Number(legacyAcademics.attendanceTarget)))migrated.attendanceTarget=Number(legacyAcademics.attendanceTarget)}if(legacyGame){migrated.xp=Math.max(Number(migrated.xp)||0,Number(legacyGame.xp)||0);migrated.streak=Math.max(Number(migrated.streak)||0,Number(legacyGame.streak)||0);migrated.lastActive=migrated.lastActive||legacyGame.lastActive||null;const legacyEvents=legacyGame.events&&typeof legacyGame.events==='object'?legacyGame.events:{};migrated.xpEvents={...legacyEvents,...(migrated.xpEvents||{})}}return sanitize(migrated)}
function sanitize(value){const s={...cloneDefaults(),...(value||{})};s.tasks=Array.isArray(s.tasks)?s.tasks.filter(t=>t&&typeof t==='object').map(t=>({id:String(t.id||globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random()}`),title:String(t.title||'').trim().slice(0,500),done:Boolean(t.done),createdAt:Number(t.createdAt)||Date.now()})).filter(t=>t.title):[];s.attendance=s.attendance&&typeof s.attendance==='object'&&!Array.isArray(s.attendance)?Object.fromEntries(Object.entries(s.attendance).filter(([,v])=>v&&typeof v==='object').map(([k,v])=>[String(k).trim().slice(0,120),{attended:Math.max(0,Math.floor(Number(v.attended)||0)),total:Math.max(0,Math.floor(Number(v.total)||0))}])):{};s.exams=Array.isArray(s.exams)?s.exams.filter(x=>x&&typeof x==='object'&&/^\d{4}-\d{2}-\d{2}$/.test(String(x.date||''))).slice(0,500):[];s.studyPlans=Array.isArray(s.studyPlans)?s.studyPlans.slice(0,1000):[];s.xp=Math.max(0,Math.floor(Number(s.xp)||0));s.streak=Math.max(0,Math.floor(Number(s.streak)||0));s.attendanceTarget=Math.min(100,Math.max(1,Number(s.attendanceTarget)||75));s.xpEvents=s.xpEvents&&typeof s.xpEvents==='object'&&!Array.isArray(s.xpEvents)?Object.fromEntries(Object.entries(s.xpEvents).map(([day,events])=>[String(day),Array.isArray(events)?events.map(String).slice(-100):[]])):{};s.schemaVersion=2;return s}
let memory=null;if(typeof window!=='undefined')window.addEventListener('storage',e=>{if(e.key===KEY||e.key===LEGACY_ACADEMICS||e.key===LEGACY_GAMIFICATION)memory=null});
export function load(){if(memory)return sanitize(memory);memory=migrate();try{localStorage.setItem(KEY,JSON.stringify(memory));localStorage.removeItem(LEGACY_ACADEMICS);localStorage.removeItem(LEGACY_GAMIFICATION)}catch{}return sanitize(memory)}
export function save(state){memory=sanitize(state);try{localStorage.setItem(KEY,JSON.stringify(memory))}catch{}return sanitize(memory)}
export function patch(values){return save({...load(),...values})}
export function addTask(title){const value=String(title||'').trim().slice(0,500);if(!value)throw new Error('Task is required');const s=load(),task={id:globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`,title:value,done:false,createdAt:Date.now()};s.tasks.unshift(task);save(s);awardXp(5,`task-added:${task.id}`);return load()}
export function toggleTask(id){const s=load(),t=s.tasks.find(x=>x.id===id);if(!t)return s;const was=t.done;t.done=!t.done;save(s);if(t.done&&!was)awardXp(10,`task-completed:${t.id}`);else if(was&&!t.done){const current=load();save({...current,xp:Math.max(0,current.xp-10)})}return load()}
export function addXp(amount){return awardXp(amount,'manual')}
export function awardXp(amount,event='general'){const n=Math.max(0,Math.min(100,Math.floor(Number(amount)||0)));if(!n)return load().xp;const s=load(),day=isoNow(),events={...s.xpEvents},eventKey=String(event||'general').slice(0,200),dayEvents=Array.isArray(events[day])?events[day].map(String):[];if(eventKey.startsWith('once:')&&dayEvents.includes(eventKey))return s.xp;events[day]=[...dayEvents,eventKey].slice(-100);const cutoff=Date.now()-180*86400000;for(const key of Object.keys(events)){if(Date.parse(`${key}T00:00:00Z`)<cutoff)delete events[key]}s.xp+=n;save({...s,xp:s.xp,xpEvents:events});return s.xp}
export function recordActivity(date=new Date()){const s=load(),day=localIso(date);if(s.lastActive===day)return s.streak;const prev=s.lastActive?new Date(`${s.lastActive}T00:00:00`):null,cur=new Date(`${day}T00:00:00`),diff=prev?Math.round((cur-prev)/86400000):null,streak=diff===1?s.streak+1:1;return save({...s,streak,lastActive:day}).streak}
export function setTheme(theme){return patch({theme:['system','light','dark'].includes(theme)?theme:'system'})}
export function applyTheme(){const s=load(),media=matchMedia('(prefers-color-scheme: dark)'),dark=s.theme==='dark'||(s.theme==='system'&&media.matches);document.body.classList.toggle('dark',dark)}
export function stateKey(){return KEY}
