const KEY='saiu-v2-state';
const LEGACY_ACADEMICS='saiu-v2-academics';
const LEGACY_GAMIFICATION='saiu-v2-gamification';
const defaults={theme:'system',school:'SCDS',section:'SCDS 3',tasks:[],xp:0,streak:0,lastActive:null,lastOpen:null,installDismissed:false,attendanceTarget:75,attendance:{},exams:[],studyPlans:[],xpEvents:{},schemaVersion:2};
const cloneDefaults=()=>({theme:defaults.theme,school:defaults.school,section:defaults.section,tasks:[],xp:0,streak:0,lastActive:null,lastOpen:null,installDismissed:false,attendanceTarget:defaults.attendanceTarget,attendance:{},exams:[],studyPlans:[],xpEvents:{},schemaVersion:2});
const isoNow=()=>new Date().toISOString().slice(0,10);
function parse(raw){try{return raw?JSON.parse(raw):null}catch{return null}}
function migrate(){const base=cloneDefaults();const legacyAcademics=parse(localStorage.getItem(LEGACY_ACADEMICS));const legacyGame=parse(localStorage.getItem(LEGACY_GAMIFICATION));const migrated={...base,...(parse(localStorage.getItem(KEY))||{})};if(legacyAcademics){if(!migrated.attendance||!Object.keys(migrated.attendance).length)migrated.attendance=legacyAcademics.attendance&&typeof legacyAcademics.attendance==='object'?legacyAcademics.attendance:{};if(!migrated.exams?.length)migrated.exams=Array.isArray(legacyAcademics.exams)?legacyAcademics.exams:[];if(!migrated.studyPlans?.length)migrated.studyPlans=Array.isArray(legacyAcademics.studyPlans)?legacyAcademics.studyPlans:[];if(migrated.attendanceTarget===75&&Number.isFinite(Number(legacyAcademics.attendanceTarget)))migrated.attendanceTarget=Number(legacyAcademics.attendanceTarget)}if(legacyGame){migrated.xp=Math.max(Number(migrated.xp)||0,Number(legacyGame.xp)||0);migrated.streak=Math.max(Number(migrated.streak)||0,Number(legacyGame.streak)||0);migrated.lastActive=migrated.lastActive||legacyGame.lastActive||null;const legacyEvents=legacyGame.events&&typeof legacyGame.events==='object'?legacyGame.events:{};migrated.xpEvents={...legacyEvents,...(migrated.xpEvents||{})}}return sanitize(migrated)}
function sanitize(value){const s={...cloneDefaults(),...(value||{})};s.tasks=Array.isArray(s.tasks)?s.tasks.filter(t=>t&&typeof t==='object').map(t=>({id:String(t.id||crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`),title:String(t.title||'').trim().slice(0,500),done:Boolean(t.done),createdAt:Number(t.createdAt)||Date.now()})).filter(t=>t.title):[];s.attendance=s.attendance&&typeof s.attendance==='object'&&!Array.isArray(s.attendance)?Object.fromEntries(Object.entries(s.attendance).filter(([k,v])=>v&&typeof v==='object').map(([k,v])=>[String(k).trim().slice(0,120),{attended:Math.max(0,Math.floor(Number(v.attended)||0)),total:Math.max(0,Math.floor(Number(v.total)||0))}])):{};s.exams=Array.isArray(s.exams)?s.exams.filter(x=>x&&typeof x==='object'&&/^\d{4}-\d{2}-\d{2}$/.test(String(x.date||''))).slice(0,500):[];s.studyPlans=Array.isArray(s.studyPlans)?s.studyPlans.slice(0,1000):[];s.xp=Math.max(0,Math.floor(Number(s.xp)||0));s.streak=Math.max(0,Math.floor(Number(s.streak)||0));s.attendanceTarget=Math.min(100,Math.max(1,Number(s.attendanceTarget)||75));s.xpEvents=s.xpEvents&&typeof s.xpEvents==='object'&&!Array.isArray(s.xpEvents)?s.xpEvents:{};s.schemaVersion=2;return s}
let memory=null;
export function load(){if(memory)return sanitize(memory);memory=migrate();localStorage.setItem(KEY,JSON.stringify(memory));localStorage.removeItem(LEGACY_ACADEMICS);localStorage.removeItem(LEGACY_GAMIFICATION);return sanitize(memory)}
export function save(state){memory=sanitize(state);localStorage.setItem(KEY,JSON.stringify(memory));return sanitize(memory)}
export function patch(values){return save({...load(),...values})}
export function addTask(title){const value=String(title||'').trim().slice(0,500);if(!value)throw new Error('Task is required');const s=load();s.tasks.unshift({id:crypto.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`,title:value,done:false,createdAt:Date.now()});awardXp(5,'task-added');return load()}
export function toggleTask(id){const s=load();const t=s.tasks.find(x=>x.id===id);if(t){const was=t.done;t.done=!t.done;if(t.done&&!was)awardXp(10,'task-completed');else if(was&&!t.done)patch({xp:Math.max(0,load().xp-10)})}return load()}
export function addXp(amount){return awardXp(amount,'manual')}
export function awardXp(amount,event='general'){const n=Math.max(0,Math.min(100,Math.floor(Number(amount)||0)));if(!n)return load().xp;const s=load();const day=isoNow();const events={...s.xpEvents};const dayEvents=Array.isArray(events[day])?events[day]:[];if(dayEvents.includes(event))return s.xp;events[day]=[...dayEvents,event].slice(-100);const cutoff=Date.now()-180*86400000;for(const key of Object.keys(events)){if(Date.parse(`${key}T00:00:00Z`)<cutoff)delete events[key]}s.xp+=n;save({...s,xp:s.xp,xpEvents:events});return s.xp}
export function recordActivity(date=new Date()){const s=load();const day=new Date(date).toISOString().slice(0,10);if(s.lastActive===day)return s.streak;const prev=s.lastActive?new Date(`${s.lastActive}T00:00:00`):null;const cur=new Date(`${day}T00:00:00`);const diff=prev?Math.round((cur-prev)/86400000):null;const streak=diff===1?s.streak+1:1;return save({...s,streak,lastActive:day}).streak}
export function setTheme(theme){return patch({theme:['system','light','dark'].includes(theme)?theme:'system'})}
export function applyTheme(){const s=load();const media=matchMedia('(prefers-color-scheme: dark)');const dark=s.theme==='dark'||(s.theme==='system'&&media.matches);document.body.classList.toggle('dark',dark)}
export function stateKey(){return KEY}
