import {load,save} from './store.js';
const localIso=date=>{const d=new Date(date);return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`};
export function academics(){const s=load();return {attendanceTarget:s.attendanceTarget,attendance:s.attendance,exams:s.exams,studyPlans:s.studyPlans}}
function saveAcademics(value){const s=load();return save({...s,...value})}
export function attendanceStatus(attended,total,target=load().attendanceTarget){const a=Math.max(0,Math.floor(Number(attended)||0)),t=Math.max(0,Math.floor(Number(total)||0)),goal=Math.min(100,Math.max(1,Number(target)||75));if(a>t)throw new Error('Attended classes cannot exceed total classes');const pct=t?a/t*100:0;const atRisk=pct<goal;const classesNeeded=atRisk&&goal<100?Math.ceil((goal*t-100*a)/(100-goal)):0;return {attended:a,total:t,pct,atRisk,classesNeeded,target:goal}}
export function setAttendance(subject,attended,total){const key=String(subject||'').trim();if(!key)throw new Error('Subject is required');const status=attendanceStatus(attended,total);const a=load();a.attendance[key]={attended:status.attended,total:status.total};save(a);return a.attendance[key]}
export function removeAttendance(subject){const a=load();delete a.attendance[String(subject||'')];save(a)}
export function attendanceSummary(){const a=load();return Object.entries(a.attendance).map(([subject,v])=>({subject,...v,...attendanceStatus(v.attended,v.total,a.attendanceTarget)})).sort((x,y)=>x.pct-y.pct)}
function validIsoDate(value){if(!/^\d{4}-\d{2}-\d{2}$/.test(value))return false;const d=new Date(`${value}T12:00:00`);return !Number.isNaN(d.getTime())&&localIso(d)===value}
export function addExam(exam){const a=load();const name=String(exam?.name||'').trim().slice(0,200);const date=String(exam?.date||'').trim();if(!name||!validIsoDate(date))throw new Error('Exam name and valid date are required');const item={id:globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`,name,date,course:String(exam.course||'').trim().slice(0,200),notes:String(exam.notes||'').trim().slice(0,2000),createdAt:new Date().toISOString()};a.exams=[...a.exams.filter(x=>x.id!==item.id),item].sort((x,y)=>x.date.localeCompare(y.date)).slice(0,500);save(a);return item}
export function removeExam(id){const a=load();a.exams=a.exams.filter(x=>x.id!==id);save(a)}
export function upcomingExams(from=new Date()){const base=localIso(from);return load().exams.filter(x=>validIsoDate(x.date)&&x.date>=base).sort((a,b)=>a.date.localeCompare(b.date))}
export function daysUntil(date,from=new Date()){if(!validIsoDate(date))return NaN;const base=localIso(from);const [by,bm,bd]=base.split('-').map(Number),[ty,tm,td]=date.split('-').map(Number);return Math.round((Date.UTC(ty,tm-1,td)-Date.UTC(by,bm-1,bd))/86400000)}
export function buildStudyPlan(exams,freeSlots,days=7,from=new Date()){const plan=[];const list=(exams||[]).filter(e=>e&&validIsoDate(e.date)).sort((a,b)=>a.date.localeCompare(b.date));const base=new Date(from);base.setHours(0,0,0,0);for(let d=0;d<Math.max(0,Math.min(30,Number(days)||0));d++){const date=new Date(base);date.setDate(date.getDate()+d);const iso=localIso(date);const exam=list.find(e=>daysUntil(e.date, date)<=7&&daysUntil(e.date,date)>=0);if(!exam)continue;const slots=(freeSlots(iso)||[]).filter(s=>Number.isFinite(s?.start)&&Number.isFinite(s?.end)&&s.end>s.start);const minutes=slots.reduce((n,s)=>n+Math.min(90,Math.max(0,s.end-s.start)),0);if(minutes>0)plan.push({date:iso,focus:exam.course||exam.name,minutes,examId:exam.id})}return plan}
export function saveStudyPlan(plan){const safe=Array.isArray(plan)?plan.filter(x=>x&&x.date&&x.focus&&Number(x.minutes)>0).slice(0,1000):[];return saveAcademics({studyPlans:safe}).studyPlans}
export function clearAcademics(){saveAcademics({attendance:{},exams:[],studyPlans:[]})}
