const KEY='saiu-v2-academics';
const defaults={attendanceTarget:75,attendance:{},exams:[],studyPlans:[]};
const cloneDefaults=()=>({attendanceTarget:defaults.attendanceTarget,attendance:{},exams:[],studyPlans:[]});
export function academics(){try{const raw=JSON.parse(localStorage.getItem(KEY)||'{}');return {...cloneDefaults(),...raw,attendance:{...defaults.attendance,...raw.attendance},exams:Array.isArray(raw.exams)?raw.exams:[],studyPlans:Array.isArray(raw.studyPlans)?raw.studyPlans:[]}}catch{return cloneDefaults()}}
export function saveAcademics(value){const next={...academics(),...value};localStorage.setItem(KEY,JSON.stringify(next));return next}
export function attendanceStatus(attended,total,target=academics().attendanceTarget){const a=Math.max(0,Number(attended)||0),t=Math.max(0,Number(total)||0),goal=Math.min(100,Math.max(1,Number(target)||75));const pct=t?a/t*100:0;const atRisk=pct<goal;const classesNeeded=atRisk&&goal<100?Math.ceil((goal*t-100*a)/(100-goal)):0;return {attended:a,total:t,pct,atRisk,classesNeeded,target:goal}}
export function setAttendance(subject,attended,total){const a=academics();const key=String(subject||'').trim();if(!key)throw new Error('Subject is required');a.attendance[key]={attended:Math.max(0,Number(attended)||0),total:Math.max(0,Number(total)||0)};saveAcademics(a);return a.attendance[key]}
export function removeAttendance(subject){const a=academics();delete a.attendance[String(subject||'')];saveAcademics(a)}
export function attendanceSummary(){const a=academics();return Object.entries(a.attendance).map(([subject,v])=>({subject,...v,...attendanceStatus(v.attended,v.total,a.attendanceTarget)})).sort((x,y)=>x.pct-y.pct)}
export function addExam(exam){const a=academics();const name=String(exam?.name||'').trim();const date=String(exam?.date||'').trim();if(!name||!/^(\d{4})-(\d{2})-(\d{2})$/.test(date))throw new Error('Exam name and valid date are required');const item={id:globalThis.crypto?.randomUUID?.()||`${Date.now()}-${Math.random().toString(36).slice(2)}`,name,date,course:String(exam.course||'').trim(),notes:String(exam.notes||'').trim(),createdAt:new Date().toISOString()};a.exams=[...a.exams.filter(x=>x.id!==item.id),item].sort((x,y)=>x.date.localeCompare(y.date));saveAcademics(a);return item}
export function removeExam(id){const a=academics();a.exams=a.exams.filter(x=>x.id!==id);saveAcademics(a)}
export function upcomingExams(from=new Date()){const base=new Date(from);base.setHours(0,0,0,0);return academics().exams.filter(x=>new Date(`${x.date}T00:00:00`)>=base).sort((a,b)=>a.date.localeCompare(b.date))}
export function daysUntil(date,from=new Date()){const a=new Date(from);const b=new Date(`${date}T00:00:00`);a.setHours(0,0,0,0);return Math.ceil((b-a)/86400000)}
export function buildStudyPlan(exams,freeSlots,days=7){const plan=[];const list=(exams||[]).filter(Boolean).sort((a,b)=>String(a.date).localeCompare(String(b.date)));for(let d=0;d<days;d++){const date=new Date();date.setHours(0,0,0,0);date.setDate(date.getDate()+d);const iso=date.toISOString().slice(0,10);const exam=list.find(e=>daysUntil(e.date,date)<=7&&daysUntil(e.date,date)>=0);if(exam){const slots=freeSlots(iso)||[];plan.push({date:iso,focus:exam.course||exam.name,minutes:slots.reduce((n,s)=>n+Math.min(90,Math.max(0,s.end-s.start)),0),examId:exam.id})}}return plan}
export function saveStudyPlan(plan){return saveAcademics({studyPlans:Array.isArray(plan)?plan:[]}).studyPlans}
export function clearAcademics(){localStorage.removeItem(KEY)}
